# Generated by Django 5.2.6 on 2025-09-22 21:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='boost',
            name='boost_type',
            field=models.CharField(choices=[('double_points', 'Удвоением очков'), ('speed', 'Ускорение'), ('shield', 'Щит')], max_length=50),
        ),
    ]
